# Настройка golangci-lint

run:
  # Количество одновременно выполняемых линтеров. Увеличьте, если у вас многоядерный процессор.
  concurrency: 4
  # Пропускать файлы, которые не были изменены в последнем коммите.
  skip-files:
    - ".*_generated.go" # Пропускаем сгенерированные файлы
    - ".*.pb.go"       # Пропускаем protobuf файлы
  # Максимальный размер файла для линтинга (в килобайтах). Большие файлы могут замедлять процесс.
  max-same-issues: 0 # Отключаем ограничение на количество одинаковых ошибок

# Линтеры, которые будут запущены.
linters:
  enable:
    - asasalint         # Поиск присваиваний переменным, которые никогда не используются
    - bidichk           # Проверка на скрытые символы Unicode (BiDi)
    - bodyclose           # Проверка на отсутствие закрытия тела ответа HTTP
    - deadcode          # Поиск неиспользуемого кода
    - depguard          # Проверка импорта запрещенных пакетов
    - dogsled           # Поиск повторяющихся объявлений var/const в одном блоке
    - dupl              # Поиск дублирования кода
    - errcheck          # Проверка на игнорирование ошибок
    - exhaustive        # Проверка полноты switch statement
    - gofmt             # Проверка форматирования кода с помощью gofmt
    - goimports         # Проверка организации импортов (аналогично gofmt -s)
    - gosimple          # Поиск упрощений кода
    - govet             # Запуск стандартного пакета govet
    - ineffassign       # Поиск присваиваний, которые никогда не используются
    - misspell          # Поиск опечаток
    - nakedret          # Поиск naked returns (когда функция возвращает несколько значений, но return statement не указывает их явно)
    - revive            # Более строгий linter, чем golint
    - staticcheck       # Обширный набор статических проверок
    - structcheck       # Поиск неиспользуемых полей структуры
    - stylecheck        # Проверка стиля кода
    - unconvert         # Поиск ненужных преобразований типов
    - unparam           # Поиск неиспользуемых параметров функции
    - unused            # Поиск неиспользуемых переменных и функций

# Настройка отдельных линтеров
linters-settings:
  depguard:
    list-type: blacklist  # Запрещаем использование определенных пакетов
    include-go-root: false  # Не проверять пакеты из стандартной библиотеки
    packages:
      - github.com/sirupsen/logrus  # Пример: Запрещаем использование logrus

# Скипаем определенные файлы
skip-dirs:
   - ./api/generated/go # Скипаем сгенерированный код